export { buildReplCompleter } from './core/commands.ts';
export type { PadroneOptions } from './core/create.ts';
export { createPadrone, defineArgsMeta, defineCommand } from './core/create.ts';
export type { PadroneErrorOptions } from './core/errors.ts';
export {
  ActionError,
  ConfigError,
  PadroneError,
  PromptCancelledError,
  PromptUnavailableError,
  RoutingError,
  SignalError,
  ValidationError,
} from './core/errors.ts';
export { defineEvent } from './core/events.ts';
export { defineInterceptor, LOCAL_CALLERS, REMOTE_CALLERS } from './core/interceptors.ts';
export type { PadroneCommandNotFound } from './core/not-found.ts';
export { commandNotFound } from './core/not-found.ts';
export type { OptionArity } from './core/parse.ts';
export { asyncSchema } from './core/results.ts';
export type {
  InteractiveMode,
  InteractivePromptConfig,
  PadroneBarAnimation,
  PadroneBarChar,
  PadroneBarConfig,
  PadroneProgress,
  PadroneProgressOptions,
  PadroneProgressPersistOptions,
  PadroneProgressShow,
  PadroneProgressUpdate,
  PadroneRuntime,
  PadroneSignal,
  PadroneSpinnerConfig,
  PadroneSpinnerPreset,
} from './core/runtime.ts';
export { PROMPT_CANCEL, REPL_SIGINT } from './core/runtime.ts';
export type {
  ConfigSearchOptions,
  HelpCommand,
  HelpTopicInfo,
  PadroneAliasesOptions,
  PadroneAutoOutputOptions,
  PadroneConfigContext,
  PadroneConfigExport,
  PadroneConfigOptions,
  PadroneConfigProfilesOptions,
  PadroneConfirmOptions,
  PadroneCredentials,
  PadroneCredentialsOptions,
  PadroneEnvOptions,
  PadroneExternalCommandsOptions,
  PadroneFormatColumns,
  PadroneFormatOptions,
  PadroneHelpOptions,
  PadroneHelpTopic,
  PadroneHelpTopicContext,
  PadroneInstaller,
  PadroneJqFunction,
  PadroneJqLimits,
  PadroneJsonOptions,
  PadroneLogDestination,
  PadroneLogger,
  PadroneLoggerConfig,
  PadroneLogLevel,
  PadroneLogSerializer,
  PadroneLogStream,
  PadroneOutputFormat,
  PadronePluginPackageManager,
  PadronePluginsOptions,
  PadroneProgressConfig,
  PadroneProgressContext,
  PadroneProgressDefaults,
  PadroneProgressMessage,
  PadroneProgressMessages,
  PadroneProgressRenderer,
  PadroneResponseFilesOptions,
  PadroneSignalOptions,
  PadroneSuggestionsOptions,
  PadroneTask,
  PadroneTaskContext,
  PadroneTaskListRenderer,
  PadroneTaskRendererOptions,
  PadroneTaskState,
  PadroneTaskStatus,
  PadroneTasksFn,
  PadroneTasksOptions,
  PadroneTimingInfo,
  PadroneTimingOptions,
  PadroneUpgradeOptions,
  PadroneUpgradePlan,
  PadroneVersionCheck,
  PadroneVersionInfo,
  PadroneVersionOptions,
  VersionCommand,
  WithAsync,
  WithCredentials,
  WithHelp,
  WithLogger,
  WithProgress,
  WithRepl,
  WithVersion,
} from './extension/index.ts';
export {
  createSimpleTaskList,
  createTerminalProgress,
  createTerminalTaskList,
  defineConfig,
  detectInstaller,
  markErrorReported,
  padroneAliases,
  padroneAutoOutput,
  padroneColor,
  padroneConfig,
  padroneConfirm,
  padroneCredentials,
  padroneEnv,
  padroneExternalCommands,
  padroneFormat,
  padroneHelp,
  padroneInteractive,
  padroneJson,
  padroneLogger,
  padronePlugins,
  padroneProgress,
  padroneRepl,
  padroneResponseFiles,
  padroneSignalHandling,
  padroneStdin,
  padroneSuggestions,
  padroneTiming,
  padroneUpdateCheck,
  padroneUpgrade,
  padroneVersion,
  redactArgs,
  verifySha256,
  verifySignature,
} from './extension/index.ts';
export type {
  PadroneCommandRunner,
  PadroneCommandRunResult,
  PadroneCredentialBackend,
} from './feature/credentials.ts';
export { fileCredentialBackend, macosKeychainBackend, secretServiceBackend } from './feature/credentials.ts';
export type { PadronePageOptions } from './feature/pager.ts';
export type {
  PadroneConfirmPromptOptions,
  PadroneMultiselectPromptOptions,
  PadronePasswordPromptOptions,
  PadronePrompt,
  PadronePromptChoice,
  PadronePromptContext,
  PadronePromptGroup,
  PadroneSelectPromptOptions,
  PadroneTextPromptOptions,
} from './feature/prompt.ts';
export { createPrompt, isPromptCancel } from './feature/prompt.ts';
export type { PadroneEditorOptions } from './feature/system.ts';
export type { UpdateCheckConfig, UpdateInfo } from './feature/update-check.ts';
export type { WrapConfig, WrapResult } from './feature/wrap.ts';
export type { AnsiStyle, ColorConfig, ColorTheme } from './output/colorizer.ts';
export { colorThemes } from './output/colorizer.ts';
export type { HelpDetail, HelpFormat, HelpInfo, PadroneHelpConfig, PadroneHelpContext, PadroneHelpTransform } from './output/formatter.ts';
export type { HelpSearchEntry, HelpSearchResult } from './output/help-search.ts';
export type { PadroneOutputIndicator } from './output/output-indicator.ts';
export type { KeyValueOptions, ListItem, ListOptions, TableOptions, TreeNode, TreeOptions } from './output/primitives.ts';
export type { OutputContext, OutputFormat } from './output/styling.ts';
export type {
  AnyPadroneBuilder,
  AnyPadroneCommand,
  AnyPadroneProgram,
  AsyncPadroneSchema,
  CommandTypesBase,
  DefineCommand,
  DefineCommandBuilder,
  DefineCommandContext,
  ExtractInterceptorContext,
  ExtractInterceptorRequires,
  GetArgsMeta,
  InterceptorBaseContext,
  InterceptorDefBuilder,
  InterceptorErrorContext,
  InterceptorErrorResult,
  InterceptorExecuteContext,
  InterceptorExecuteResult,
  InterceptorFactory,
  InterceptorMeta,
  InterceptorParseContext,
  InterceptorParseResult,
  InterceptorPhases,
  InterceptorRouteContext,
  InterceptorShutdownContext,
  InterceptorStartContext,
  InterceptorValidateContext,
  InterceptorValidateResult,
  MaybePromiseCommandResult,
  PadroneActionContext,
  PadroneAPI,
  PadroneBuilder,
  PadroneCaller,
  PadroneCommand,
  PadroneCommandComplete,
  PadroneCommandResult,
  PadroneCompleteContext,
  PadroneCompletionDirective,
  PadroneCompletionItem,
  PadroneCompletionResult,
  PadroneContextInterceptor,
  PadroneDrainResult,
  PadroneEmit,
  PadroneEvent,
  PadroneEventContext,
  PadroneEventHandler,
  PadroneExpose,
  PadroneExtension,
  PadroneExtraCommand,
  PadroneFieldGroups,
  PadroneGlobalArgsMeta,
  PadroneHookContext,
  PadroneHookName,
  PadroneInput,
  PadroneInterceptor,
  PadroneInterceptorFn,
  PadroneParseResult,
  PadroneProgram,
  PadroneProgramMeta,
  PadroneRunCommand,
  PadroneSchema,
  PadroneValueHint,
  RegisteredInterceptor,
} from './types/index.ts';
export type { PadroneDirs } from './util/dirs.ts';
export { getProgramDirs } from './util/dirs.ts';
export type { AsyncStreamMeta } from './util/stream.ts';
export { asyncStream } from './util/stream.ts';
export type {
  InferArgsInput,
  InferArgsOutput,
  InferCommand,
  InferContext,
  InferContextProvided,
  InferInterceptorContext,
  InferInterceptorRequires,
} from './util/type-helpers.ts';
export type { Drained, MaybePromise, Thenable } from './util/type-utils.ts';
